### ISSUE TITLE
Cannot Open App

### ISSUE THREAD

**Issue by alamodeg** [BD9a/poe-live-search-manager-fix#1]
I cannot open the program :( . Justo manually change PoE for BoE

**Comment by Shortbread304** [comment]
It didn't work for me at first either.  I used basic notepad, and upon resaving the .asar file the program wouldn't open.  I uninstalled live search manager.  Installed notepadd ++, and repeated the process with notepadd ++ as the author suggested.  Worked.  Live searches connecting.

**Comment by alamodeg** [comment]
> 
> 
> It didn't work for me at first either. I used basic notepad, and upon resaving the .asar file the program wouldn't open. I uninstalled live search manager. Installed notepadd ++, and repeated the process with notepadd ++ as the author suggested. Worked. Live searches connecting.

Im stupid AF . All my life thought note++ is the default text editor ^^.  It worked thank you sir and the author too

**Comment by lordbard** [comment]
Worked for me too.!!! I recommend folks don't all use same name for their user agent.  If the user agent gets banned again, then it will stop working for all. Maybe instead of using BOE use your initials.

**Comment by BD9a** [comment]
Yeah, if You follow the guide it should work for You perfectly. I will close this issue then. Just follow the instructions!
